---
- name: Enable Web Server on KVM host
  hosts: kvm 
  tasks: 
    - name: Create Kickstart Directory
      file:
        path: "{{ kickstart_path }}"
        state: directory

    - name: Start Web Server for Kickstarts
      simplehttpserver:
        port: "{{ webserver_port }}" 
        path: "{{ kickstart_path }}"
      async: 600
      poll: 0
      register: web

- name: Create Virtual Machines
  hosts: virtualmachines
  roles:
    - { role: virt-install }


      #    - name: Check webserver
      #      async_status:
      #        jid: "{{ web.ansible_job_id }}"
      #      register: job_result
      #      until: job_result.finished
      #      retries: 60
      #      delay: 10
