---
ip_address: 10.53.250.5
hostname: example 
domainname: example.com
name: "{{ hostname }}"

vcpus: 2
memory: 4096
disk_size: 64
redirect_on_write: True

os_variant: "centos7.0"
disks: 
  - "path={{ instance_path }}/{{ name }}.qcow2,size={{ disk_size }}"
networks:
  - 'network=ovsbr0,portgroup=vlan-250,model=virtio'
