---
ip_address: 10.0.0.10
hostname: example-node 
domainname: example.com
name: "{{ hostname }}"
disks: 
  - 'path=/instances/{{ name }}.qcow2,size=64'
networks:
  - 'network=ovsbr0,portgroup=vlan-10'
