---
- name: "power {{ inventory_hostname }} on"
  virt:
    name: "{{ inventory_hostname }}"
    command: start
  when: redirect_on_write is not defined or not redirect_on_write

- name: retrieve ip address
  virt_ipaddress:
    name: "{{ inventory_hostname }}" 
    device: "eth0"
  register: guest
  until: guest | success
  retries: 6
  delay: 10
  delegate_to: kvm
  ignore_errors: True

- name: Set correct IP Address to run tasks
  set_fact:
    ansible_ssh_host: "{{ guest.ansible_virt_ipv4 }}"

# the machine might have received an address but    
- name: Wait for ssh to be available
  local_action: 
    module: wait_for 
    host: "{{ ansible_ssh_host }}" 
    state: started
    port: 22
    delay: 30
    connect_timeout: 15
    timeout: 300
