---
#- name: find a centos mirror
#  uri:
  #    url: "http://mirrorlist.centos.org/?release={{ releasever }}&arch=x86_64&repo=os" 
  #   return_content: True
  #register: mirrorlist

- name: create kickstart directory
  file:
    path: "{{ kickstart_path }}"
    state: directory

- name: create kickstart
  template:
    src: ks.cfg.j2
    dest: "{{ kickstart_path }}/{{ name }}.cfg"

- name: "virt-install {{ name }}"
  virt_install:
    name: "{{ name }}" 
    vcpus: 2
    memory: 4096
    #vcpus: "{{ vcpus }}"
    #memory: "{{ memory }}"
    #location: "{{ mirrorlist.content.split('\n') | random }}" 
    location: "{{ mirror_list | random }}" 
    disks: "{{ disks }}"
    networks: "{{ networks }}"
    #    os_variant: "{{ os_variant }}"
    extra_args: "{{ extra_args }}"

- name: "wait until {{ name }} to power off" 
  virt:
    name: "{{ name }}"
    command: status
  register: result
  until: result.status.find("shutdown") != -1
  retries: 60
  delay: 30
